config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView

urlpatterns = [
    path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path("about/", TemplateView.as_view(template_name="pages/about.html"), name="about"),
    path("about/gout/", TemplateView.as_view(template_name="pages/about_gout.html"), name="about-gout"),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("goutdotcom.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
    # Reference for app URLs with Cookiecutter-Django: https://stackoverflow.com/questions/39838290/is-there-a-command-for-creating-an-app-using-cookiecutter-django
    path("profiles/", include(("goutdotcom.profiles.urls"), namespace="profiles")),
    path("lab/", include(("goutdotcom.lab.urls"), namespace="lab")),
    path("flare/", include(("goutdotcom.flare.urls"), namespace="flare")),
    path("flareaid/", include(("goutdotcom.flareaid.urls"), namespace="flareaid")),
    path("history/", include(("goutdotcom.history.urls"), namespace="history")),
    path("ppxaid/", include(("goutdotcom.ppxaid.urls"), namespace="ppxaid")),
    path("ult/", include(("goutdotcom.ult.urls"), namespace="ult")),
    path("ultaid/", include(("goutdotcom.ultaid.urls"), namespace="ultaid")),
    path("ultplan/", include(("goutdotcom.ultplan.urls"), namespace="ultplan")),
    path("treatment/", include(("goutdotcom.treatment.urls"), namespace="treatment")),
    path("vitals/", include(("goutdotcom.vitals.urls"), namespace="vitals")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

goutdotcom/flare/urls.py
from django.urls import path

from .views import AboutFlares, FlareCreate, FlareDetail, FlareList, FlareUpdate

app_name = "flare"
urlpatterns = [
    path("about/", view=AboutFlares.as_view(), name="about"),
    path("create/", view=FlareCreate.as_view(), name="create"),
    path("<int:pk>/", view=FlareDetail.as_view(), name="detail"),
    path("<slug:slug>/", view=FlareDetail.as_view(), name="user-detail"),
    path("<slug:username>/create/", view=FlareCreate.as_view(), name="user-create"),
    path("<slug:slug>/update/", view=FlareUpdate.as_view(), name="update"),
    path("list/<slug:username>/", view=FlareList.as_view(), name="list"),
]

goutdotcom/lab/urls.py
from django.urls import path

from .views import (
    IndexView,
    LabAbout,
    LabCheckCreate,
    LabCheckUpdate,
    LabCreate,
    LabDetail,
    LabList,
    LabUpdate,
)

app_name = "lab"
urlpatterns = [
    path("", view=IndexView.as_view(), name="index"),
    path("about/<lab>/", view=LabAbout.as_view(), name="about"),
    path("create/labcheck/", view=LabCheckCreate.as_view(), name="labcheck-create"),
    path("create/<lab>/", view=LabCreate.as_view(), name="create"),
    path("<slug:username>/create/<lab>/", view=LabCreate.as_view(), name="user-create"),
    path("create/<lab>/ultplan/<int:ultplan>/", view=LabCreate.as_view(), name="single-ultplan-create"),
    path("<slug:username>/list/<lab>/", view=LabList.as_view(), name="list"),
    path("update/labcheck/<slug:slug>/", view=LabCheckUpdate.as_view(), name="labcheck-update"),
    path("update/<lab>/<slug:slug>/", view=LabUpdate.as_view(), name="update"),
    path("<lab>/<slug:slug>/", view=LabDetail.as_view(), name="detail"),
]

goutdotcom/treatment/urls.py
from django.urls import path

from .views import *

app_name = "treatment"
urlpatterns = [
    path("about/", view=About.as_view(), name="about"),
    path("about/corticosteroids/", view=AboutCorticosteroids.as_view(), name="about-corticosteroids"),
    path("about/flare/", view=AboutFlare.as_view(), name="about-flare"),
    path("about/nsaids/", view=AboutNSAIDs.as_view(), name="about-NSAIDs"),
    path("about/prophylaxis/", view=AboutProphylaxis.as_view(), name="about-prophylaxis"),
    path("about/ult/", view=AboutULT.as_view(), name="about-ult"),
    path("about/<treatment>", view=TreatmentAbout.as_view(), name="about"),
    path("<slug:username>/", view=IndexView.as_view(), name="index"),
    path("<slug:username>/flare/", FlareView.as_view(), name="flare"),
    path("<slug:username>/prophylaxis/", ProphylaxisView.as_view(), name="prophylaxis"),
    path("<slug:username>/ult/", ULTView.as_view(), name="ult"),
    path("<treatment>/<slug:slug>/", view=TreatmentDetail.as_view(), name="detail"),
    path("<slug:username>/list/<treatment>/", view=TreatmentList.as_view(), name="list"),
    path("<slug:username>/create/<treatment>/", view=TreatmentCreate.as_view(), name="create"),
    path(
        "<slug:username>/create/flareaid/<slug:slug>/<treatment>/",
        view=FlareAidTreatmentCreate.as_view(),
        name="flareaid-create",
    ),
    path("<slug:username>/create/ppx/<treatment>/", view=ProphylaxisCreate.as_view(), name="prophylaxis-create"),
    path("update/<treatment>/<slug:slug>/", view=TreatmentUpdate.as_view(), name="update"),
]

goutdotcom/ult/urls.py
from django.urls import path

from .views import ULTCreate, ULTDetail, ULTUpdate

app_name = "ult"
urlpatterns = [
    path("create/", view=ULTCreate.as_view(), name="create"),
    path("<username>/create/", view=ULTCreate.as_view(), name="user-create"),
    path("<int:pk>/", view=ULTDetail.as_view(), name="detail"),
    path("<slug:slug>/", view=ULTDetail.as_view(), name="user-detail"),
    path("update/<int:pk>/", view=ULTUpdate.as_view(), name="update"),
    path("<slug:slug>/update/", view=ULTUpdate.as_view(), name="user-update"),
]

goutdotcom/lab/models.py
from datetime import datetime, timedelta
from decimal import Decimal
from math import ceil
from statistics import mean

from django.conf import settings
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from django.db.models.fields import BooleanField
from django.urls import reverse
from django.utils import timezone
from django.utils.text import slugify
from django_extensions.db.models import TimeStampedModel
from simple_history.models import HistoricalRecords

from ..lab.choices import BOOL_CHOICES, CELLSMM3, GDL, MGDL, PLTMICROL, UL, UNIT_CHOICES


def round_decimal(value, places):
    if value is not None:
        # see https://docs.python.org/2/library/decimal.html#decimal.Decimal.quantize for options
        return value.quantize(Decimal(10) ** -places)
    return value


class Lab(TimeStampedModel):
    def class_name(self):
        return self.__class__.__name__

    class Flag(models.IntegerChoices):
        """
        class to describe Lab.flag field choices and interpretation the Lab.value.
        Will be set by process_high() or process_low() method.
        """

        # Lab is normal, continue as normal, default value
        NORMAL = 0
        # Lab.value is high or low, but not of clinical consequence
        # Continue ULTPlan as usual
        TRIVIAL = 1
        # Lab.value is non-urgently abnormal.
        # Will not pause ULTPlan
        NONURGENT = 2
        # Lab.value is urgently abnormal.
        # WILL PAUSE ULTPLAN
        URGENT = 3
        # Lab.value is emergently abnormal.
        # WILL PAUSE ULPLAN
        # WILL RECOMMEND SEEKING IN PERSON MEDICAL CONSULTATION
        EMERGENCY = 4
        # Lab.value is close to normal.
        # Set when a Lab is a follow-up (has abnormal_followup field)
        RESOLVED = 5
        # Lab.value is stable from the last abnormal check
        STABLE = 6
        # Lab.value is improving from the last abnormal check.
        IMPROVING = 7

    class Action(models.IntegerChoices):
        """
        Class to describe Lab.action field choices and action taken on abnormal Lab.
        Will be set by process_high() or process_low() method.
        """

        # Continue the ULTPlan as normal
        CONTINUE = 0
        # Recheck the Lab non-urgently
        # Meant for a non-urgent lab abnormality
        RECHECK = 1
        # Pause the ULTPlan and recheck the Lab urgently
        # Meant for a serious but non-emergent lab abnormality
        PAUSE = 2
        # Change the ULTPlan
        # Will also prompt inactivation of current ULTPlan in order to create a new active one
        ### TO DO: BUILD ULTPLAN change() METHOD ###
        CHANGE = 3
        # Pause the ULTPLan for an emergency, meant to be resumed or the ULTPlan stopped
        ### TO DO: BUILD ULTPLAN RESUME() and INACTIVATE() METHODS ###
        EMERGENCY = 4
        # Permanently discontinue ULTPlan
        INACTIVATE = 5

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
    )
    date_drawn = models.DateTimeField(help_text="What day was this lab drawn?", default=None, null=True, blank=True)
    abnormal_followup = models.ForeignKey("self", on_delete=models.CASCADE, null=True, blank=True, default=None)
    history = HistoricalRecords(inherit=True)
    slug = models.SlugField(max_length=200, null=True, blank=True)
    flag = models.IntegerField(
        choices=Flag.choices, default=0, validators=[MinValueValidator(0), MaxValueValidator(7)], null=True, blank=True
    )
    action = models.IntegerField(
        choices=Action.choices,
        default=0,
        validators=[MinValueValidator(0), MaxValueValidator(5)],
        null=True,
        blank=True,
    )

    class Meta:
        abstract = True

    def __str__(self):
        return f"{self.name} {self.value} {self.units}"

    def get_absolute_url(self):
        return reverse("lab:detail", kwargs={"lab": self.name, "slug": self.slug})

    def __unicode__(self):
        return self.name

    @property
    def low(self):
        """
        Function that checks whether a Lab.value is less than the lower limit of normal.

        Returns:
            bool: returns True if Lab.value is less than the lower limit of normal, False if not.
        """
        if self.value < self.reference_lower:
            return True
        else:
            return False

    @property
    def high(self):
        """
        Function that checks whether a Lab.value is greater than the upper limit of normal.

        Returns:
            bool: returns True if Lab.value is greater than the upper limit of normal, False if not.
        """
        if self.value > self.reference_upper:
            return True
        else:
            return False

    @property
    def three_x_high(self):
        """
        Function that checks whether a lab value which is greater than the upper limit of normal is greater than 3 times the upper limit of normal.

        Returns:
            bool: returns true if Lab.value is greater than 3 times the upper limit of normal
        """
        if self.value > (3 * self.reference_upper):
            return True
        else:
            return False

    @property
    def abnormal(self):
        """
        Function that checks whether or not a Lab.value is abnormal.

        Returns:
            dictionary or None: Returns a dictionary with descriptors of the Lab.value abnormality if present, otherwise returns None
        """
        # Check if lab is lower than reference range
        if self.low:
            return "L"
        elif self.high:
            if self.three_x_high:
                return "!H!"
            else:
                return "H"

    @property
    def show_flag(self):
        """
        Function that displays the Lab's flag attribute.
        Returns: string
        """
        if self.flag == 0:
            return "normal"
        elif self.flag == 1:
            return "trivial"
        elif self.flag == 2:
            return "nonurgent"
        elif self.flag == 3:
            return "urgent"
        elif self.flag == 4:
            return "emergency"
        elif self.flag == 5:
            return "resolved"
        elif self.flag == 6:
            return "stable"
        elif self.flag == 7:
            return "improving"
        else:
            return None

    @property
    def show_action(self):
        """
        Function that displays the Lab's flag attribute.
        Returns: string
        """
        if self.flag == 0:
            return "continue"
        elif self.flag == 1:
            return "recheck"
        elif self.flag == 2:
            return "pause"
        elif self.flag == 3:
            return "change"
        elif self.flag == 4:
            return "emergency"
        elif self.flag == 5:
            return "inactivate"
        else:
            return None

    def var_x_high(self, var):
        """
        Calculates if a Lab value is higher by a percentage (var).
        Tries to fetch BaselineLab for User for calculation.
        Otherwise uses reference_upper for calculation.

        Args:
            var (Float): Float percentage for calculating where the current Lab value is relative to baseline
        Returns:
            bool: True if Lab.value is > var * baseline, False if not
        """
        baseline = self.get_baseline()

        if baseline:
            if self.value > (var * baseline.value):
                return True
            else:
                return False
        else:
            if self.value > (var * self.reference_upper):
                return True
            else:
                return False

    def get_baseline(self):
        """
        Method that gets a User's Baseline for any Lab
        Returns: BaselineLab or none
        """
        return getattr(self.user, "baseline" + self.class_name().lower(), None)

    def get_labcheck(self):
        """
        Method that gets LabCheck associated with Lab
        returns: LabCheck object or None
        """
        # Check if Lab has LabCheck
        return getattr(self, "labcheck", None)

    def process_high(self):
        """
        Function that processes a high Lab.
        Checks if this object is a follow up an abnormal Lab.
        Returns "urgent" or "emergency" for emergent rise in Lab.
        Will stop ULTPlan. "emergency" will prompt a User seek immediate medical attention.
        Returns "nonurgent" for close follow-up, "trivial" for a small elevation that doesn't require immediate follow up.
        If high Lab is an abnormal follow up but not "urgent":
            Recalculates baseline in BaselineLab, checks for associated MedicalProfile object (CKD, transaminitis, leukopenia, etc.)
        Returns:
            string or nothing: returns "urgent" if urgent LabCheck follow up required, nonurgent if non-urgent required
        """
        # Assign percentages for processing high/low for scope
        trivial = None
        nonurgent = None
        urgent = None
        emergency = None

        # Check model to set percentages on which to process high values
        # Pulled from PatientProfile, which will automatically be created with default values
        if self.class_name() == "ALT" or self.class_name() == "AST":
            trivial = self.user.patientprofile.lft_trivial
            nonurgent = self.user.patientprofile.lft_nonurgent
            urgent = self.user.patientprofile.lft_urgent
            emergency = self.user.patientprofile.lft_emergency
        elif self.class_name() == "creatinine":
            trivial = self.user.patientprofile.creatinine_trivial
            nonurgent = self.user.patientprofile.creatinine_nonurgent
            urgent = self.user.patientprofile.creatinine_urgent
            emergency = self.user.patientprofile.creatinine_emergency
        elif self.class_name() == "WBC":

goutdotcom/templates/lab/_detail_buttons.html
{% load lab_extras %}
<div class="btn-group" role="group" aria-label="Button group with nested dropdown" style="float: right;">
  <div class="btn-group" role="group">
    <button id="btnGroupDrop1" type="button" class="btn btn-primary btn-lg dropdown-toggle" data-toggle="dropdown"
      aria-expanded="false">
      {{ object|to_class_name }}
    </button>
    <ul class="dropdown-menu" aria-labelledby="btnGroupDrop1" id="dropdown">
      <li><a class="dropdown-item" href="{% url 'lab:update' object|to_class_name object.pk%}">Update
</a></li>
      <li><a class="dropdown-item" href="{% url 'lab:about' object|to_class_name %}">About
</a></li>
    {% if request.user.ultplan %}
      <li><a class="dropdown-item"
          href="{% url 'lab:single-ultplan-create' object_list|list_to_name request.user.ultplan.pk %}">New
</a></li>
    {% endif %}
      <li><a class="dropdown-item" href="{% url 'lab:list' username=object.user.username lab=object|to_class_name %}">List
</a></li>
    </ul>
  </div>
</div>

goutdotcom/templates/lab/_list_buttons.html
{% load lab_extras %}
<div class="btn-group" role="group" aria-label="Button group with nested dropdown" style="float: right;">
  <div class="btn-group" role="group">
    <button id="btnGroupDrop1" type="button" class="btn btn-primary btn-lg dropdown-toggle" data-toggle="dropdown"
      aria-expanded="false">
      {{ object_list|list_to_name }}
    </button>
    <ul class="dropdown-menu" aria-labelledby="btnGroupDrop1" id="dropdown">
      <li><a class="dropdown-item" href="{% url 'lab:about' object_list|list_to_name %}">About
        </a></li>
    {% if request.user.ultplan %}
      <li><a class="dropdown-item" href="{% url 'lab:single-ultplan-create' object_list|list_to_name request.user.ultplan.pk %}">New
        </a></li>
    {% endif %}
    </ul>
  </div>
</div>

goutdotcom/templates/lab/_ultplan_lab_create_button.html
{% if request.user.ultplan %}
  <div class="btn-group" role="group" aria-label="Button group with nested dropdown" style="float: right;">
    <div class="btn-group" role="group">
      <button id="btnGroupDrop1" type="button" class="btn btn-primary btn-lg dropdown-toggle" data-toggle="dropdown"
        aria-expanded="false">
        Log a Lab
      </button>
      <ul class="dropdown-menu" aria-labelledby="btnGroupDrop1" id="dropdown">
        <li><a class="dropdown-item"
            href="{% url 'lab:single-ultplan-create' lab='urate' ultplan=request.user.ultplan.pk %}">Uric
            Acid</a>
        </li>
        <li><a class="dropdown-item"
            href="{% url 'lab:single-ultplan-create' lab='ALT' ultplan=request.user.ultplan.pk %}">ALT</a>
            </li>
        <li><a class="dropdown-item"
            href="{% url 'lab:single-ultplan-create' lab='AST' ultplan=request.user.ultplan.pk %}">AST</a>
            </li>
        <li><a class="dropdown-item"
            href="{% url 'lab:single-ultplan-create' lab='WBC' ultplan=request.user.ultplan.pk %}">WBC</a>
            </li>
        <li><a class="dropdown-item"
            href="{% url 'lab:single-ultplan-create' lab='hemoglobin' ultplan=request.user.ultplan.pk %}">Hemoglobin</a>
            </li>
        <li><a class="dropdown-item"
            href="{% url 'lab:single-ultplan-create' lab='platelet' ultplan=request.user.ultplan.pk %}">Platelets</a>
            </li>
        <li><a class="dropdown-item"
            href="{% url 'lab:single-ultplan-create' lab='creatinine' ultplan=request.user.ultplan.pk %}">Creatinine</a>
            </li>
      </ul>
    </div>
  </div>
{% endif %}

goutdotcom/templates/lab/alllabs_about.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<main>
    <div class="jumbotron-fluid content-container">
        <div class="row">
          <div class="col">
            <h1>Lab Testing and Gout</h1>
          <p class="lead">Lab testing is important in gout, particularly in diagnosis and treatment.</p>
          <hr class="my-6" color="white">
          <p>Labs are important in several gouty situations:</p>
            <ul>
                <li>Diagnosis of gout, particularly the initial diagnosis</li>
                <li>Medical <a class="link-primary" href="{% url 'treatment:about' 'about' %}">treatment</a> of gout</li>
                  <ul>
                      <li>Determining which medications are best for flares of your gout (<a href="{% url 'treatment:about-flare' %}">flare treatment</a>)</li>
                      <li>Determining the correct doses for your long-term gout medications (<a href="{% url 'treatment:about-ult' %}">ULT</a>) and monitoring for side effects</li>
                  </ul>
            </ul>
          </div>
        </div>
      <div class="row">
        <div class="col">
              <h2>Diagnosis of Gout</h2>
              <p>The diagnosis gout is clinical, but labs help. Labs can increase or decrease a provider's clinical suspicion for gout (<a class="link-primary" href="https://en.wikipedia.org/wiki/Pre-_and_post-test_probability" target="_blank">pre-test probability</a>).</p>
              <ol>
                <li>
                 Measure your serum <a class="link-primary" href="{% url 'lab:about' 'urate' %}">uric acid</a>. Very high levels make gout more likely (but not 100%). Very low levels make gout unlikely (though not impossible). Intermediate or normal levels don't help one way or the other. Serum uric acid drops during flares of gout.
                </li>
                <li>
                 We can also measure your liver(<a class="link-primary" href="{% url 'lab:about' 'AST' %}">AST</a>/<a class="link-primary" href="{% url 'lab:about' 'ALT' %}">ALT</a>) and kidney(<a class="link-primary" href="{% url 'lab:about' 'creatinine' %}">creatinine</a>) function as well as blood counts(<a class="link-primary" href="{% url 'lab:about' 'WBC' %}">WBC</a>, <a class="link-primary" href="{% url 'lab:about' 'hemoglobin' %}">hemoglobin</a>, <a class="link-primary" href="{% url 'lab:about' 'platelet' %}">platelets</a>). These are important when picking medications to treat your gout, both for the flare and for long-term management.
                </li>
              </ol>
        </div>
        <div class="col">
             <h2>Management of Gout</h2>
             <p>Labs are used in the management of gout to: </p>
             <ol>
               <li>
                Confirm that your <a class="link-primary" href="{% url 'lab:about' 'urate' %}">uric acid</a> is at goal.
               </li>
                <ul>
                  <li>The goal for uric acid is generally under 6.0 mg/dL, though some gout patients are better served with under 5.0 mg/dL.</li>
                  <li>This determines when you can stop taking medications to prevent a flare.</li>
                  <li>It also will help you and your doctor know when you are at low or no risk of having gout flares.</li>
                </ul>
               <li>
                Make sure that you aren't having any side effects from your medications.
               </li>
             </ol>
        </div>
    </div>
</main>
{% endblock content %}

goutdotcom/templates/lab/index.html
{% extends "base.html" %}
{% load static %}
{% load lab_extras %}

{% block content %}
<main role="main" class="container content-container">
    <h1 class="content-heading">{{ request.user|capfirst }}'s ULTPlan Labs<a class="btn btn-primary btn-lg" href="{% url 'lab:about' 'alllabs' %}" role="button" style="float: right;">About Labs</a>
    {% include 'lab/_ultplan_lab_create_button.html' %}
    </h1>
    <div class="row">
      <div class="col">
        {% if labs %}
          {% for lab in labs %}
            {% if lab != None %}
            <div class="container content">
              <h2><a href="{% url 'lab:list' lab|to_class_name %}">{{ lab.name|capfirst}}</h2></a>
              <ul>
                <li>{{ lab.value }} {{ lab.urate.units }}</li>
                <li>{% if lab.date_drawn %} Drawn: {{ lab.date_drawn }} {% else %} Created: {{ lab.created }}{% endif %}</li>
              </ul>
            </div>
            {% endif %}
          {% endfor %}
        {% endif %}
      </div>
    </div>
</main>
{% endblock content %}

goutdotcom/templates/lab/lab_form_base.html
{% extends "base_form.html" %}
{% load crispy_forms_tags %}
{% load lab_extras %}

{% block title %}New {{ lab }}{% endblock %}

{% block header %}
<h1 class="content-heading">New {{ lab }}</h1>
{% endblock header %}

{% block form %}
  {% if form.instance.pk %}
    <form class="form-horizontal gdc-default" method="post" action="{% url 'lab:update' lab object.pk %}">
      {% csrf_token %}
      {{ form|crispy }}
      <div class="control-group">
        <div class="controls">
          <button type="submit" class="btn btn-primary">
            Update
          </button>
        </div>
      </div>
    </form>
  {% else %}
  {% if view.kwargs.ultplan %}
    <form class="form-horizontal gdc-default" method="post"
      action="{% url 'lab:single-ultplan-create' lab=lab ultplan=view.kwargs.ultplan %}">
  {% else %}
    <form class="form-horizontal gdc-default" method="post" action="{% url 'lab:create' lab %}">
  {% endif %}
      {% csrf_token %}
      {{ form|crispy }}
      <div class="control-group">
        <div class="controls">
          <button type="submit" class="btn btn-primary">
            Create
          </button>
        </div>
      </div>
    </form>
  {% endif %}
{% endblock form %}
{% block inline_javascript %}
<link href="https://code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css" rel="stylesheet" type="text/css">
<script src="https://code.jquery.com/ui/1.13.0/jquery-ui.js"></script>
<script>
  $(function() {
  $("#id_date_drawn").datepicker();
  });
  $('#ui-datepicker-div').removeClass('ui-helper-hidden-accessible');
</script>
{% endblock inline_javascript%}

goutdotcom/templates/lab/labcheck_form.html
{% extends "base_form.html" %}
{% load crispy_forms_tags %}

{% block title %}
{% if form.instance.pk %} Update Lab Check {% else %} New Lab Check {% endif %} {% endblock%}
{% block header %}
{% if form.instance.pk %}
<h1>Update Lab Check</h1>
{% else %}
<h1>New Lab Check</h1>
{% endif %}
{% endblock header %}
{% block form %}
{% if form.instance.pk %}
  <form method="post" action="{% url 'lab:labcheck-update' slug=object.slug %}">
    {% csrf_token %}
    {% crispy form %}
    {% crispy alt_form %}
    {% crispy ast_form %}
    {% crispy creatinine_form %}
    {% crispy hemoglobin_form %}
    {% crispy platelet_form %}
    {% crispy wbc_form %}
    {% crispy urate_form %}
    <input class="btn btn-primary btn-lg" type="submit" value="Submit">
  </form>
{% else %}
  <form method="post" action="{% url 'lab:labcheck-create' %}">
    {% csrf_token %}
    {% crispy form %}
    {% crispy alt_form %}
    {% crispy ast_form %}
    {% crispy creatinine_form %}
    {% crispy hemoglobin_form %}
    {% crispy platelet_form %}
    {% crispy wbc_form %}
    {% crispy urate_form %}
    <input class="btn btn-primary btn-lg" type="submit" value="Submit">
  </form>
{% endif %}
{% endblock form %}
{% block inline_javascript %}
<script>
// this is executed once when the page loads
$(document).ready(function() {
date_drawn_checker();
});
</script>
{% endblock inline_javascript %}