config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView

urlpatterns = [
    path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path("about/", TemplateView.as_view(template_name="pages/about.html"), name="about"),
    path("about/gout/", TemplateView.as_view(template_name="pages/about_gout.html"), name="about-gout"),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("goutdotcom.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
    # Reference for app URLs with Cookiecutter-Django: https://stackoverflow.com/questions/39838290/is-there-a-command-for-creating-an-app-using-cookiecutter-django
    path("profiles/", include(("goutdotcom.profiles.urls"), namespace="profiles")),
    path("lab/", include(("goutdotcom.lab.urls"), namespace="lab")),
    path("flare/", include(("goutdotcom.flare.urls"), namespace="flare")),
    path("flareaid/", include(("goutdotcom.flareaid.urls"), namespace="flareaid")),
    path("history/", include(("goutdotcom.history.urls"), namespace="history")),
    path("ppxaid/", include(("goutdotcom.ppxaid.urls"), namespace="ppxaid")),
    path("ult/", include(("goutdotcom.ult.urls"), namespace="ult")),
    path("ultaid/", include(("goutdotcom.ultaid.urls"), namespace="ultaid")),
    path("ultplan/", include(("goutdotcom.ultplan.urls"), namespace="ultplan")),
    path("treatment/", include(("goutdotcom.treatment.urls"), namespace="treatment")),
    path("vitals/", include(("goutdotcom.vitals.urls"), namespace="vitals")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

goutdotcom/flare/urls.py
from django.urls import path

from .views import AboutFlares, FlareCreate, FlareDetail, FlareList, FlareUpdate

app_name = "flare"
urlpatterns = [
    path("about/", view=AboutFlares.as_view(), name="about"),
    path("create/", view=FlareCreate.as_view(), name="create"),
    path("<int:pk>/", view=FlareDetail.as_view(), name="detail"),
    path("<slug:slug>/", view=FlareDetail.as_view(), name="user-detail"),
    path("<slug:username>/create/", view=FlareCreate.as_view(), name="user-create"),
    path("<slug:slug>/update/", view=FlareUpdate.as_view(), name="update"),
    path("list/<slug:username>/", view=FlareList.as_view(), name="list"),
]

goutdotcom/lab/urls.py
from django.urls import path

from .views import (
    IndexView,
    LabAbout,
    LabCheckCreate,
    LabCheckUpdate,
    LabCreate,
    LabDetail,
    LabList,
    LabUpdate,
)

app_name = "lab"
urlpatterns = [
    path("", view=IndexView.as_view(), name="index"),
    path("about/<lab>/", view=LabAbout.as_view(), name="about"),
    path("create/labcheck/", view=LabCheckCreate.as_view(), name="labcheck-create"),
    path("create/<lab>/", view=LabCreate.as_view(), name="create"),
    path("<slug:username>/create/<lab>/", view=LabCreate.as_view(), name="user-create"),
    path("create/<lab>/ultplan/<int:ultplan>/", view=LabCreate.as_view(), name="single-ultplan-create"),
    path("<slug:username>/list/<lab>/", view=LabList.as_view(), name="list"),
    path("update/labcheck/<slug:slug>/", view=LabCheckUpdate.as_view(), name="labcheck-update"),
    path("update/<lab>/<slug:slug>/", view=LabUpdate.as_view(), name="update"),
    path("<lab>/<slug:slug>/", view=LabDetail.as_view(), name="detail"),
]

goutdotcom/profiles/urls.py
from django.urls import path

from .views import (
    FamilyProfileUpdate,
    MedicalProfileUpdate,
    PatientProfileUpdate,
    ProviderProfileUpdate,
    SocialProfileUpdate,
)

app_name = "profiles"
urlpatterns = [
    path("<slug:slug>/family/update/", view=FamilyProfileUpdate.as_view(), name="update-family"),
    path("<slug:slug>/medical/update/", view=MedicalProfileUpdate.as_view(), name="update-medical"),
    path("<slug:slug>/social/update/", view=SocialProfileUpdate.as_view(), name="update-social"),
    path("<slug:slug>/update/", view=PatientProfileUpdate.as_view(), name="update"),
    path("provider/<slug:slug>/update/", view=ProviderProfileUpdate.as_view(), name="provider-update"),
]

goutdotcom/treatment/urls.py
from django.urls import path

from .views import *

app_name = "treatment"
urlpatterns = [
    path("about/", view=About.as_view(), name="about"),
    path("about/corticosteroids/", view=AboutCorticosteroids.as_view(), name="about-corticosteroids"),
    path("about/flare/", view=AboutFlare.as_view(), name="about-flare"),
    path("about/nsaids/", view=AboutNSAIDs.as_view(), name="about-NSAIDs"),
    path("about/prophylaxis/", view=AboutProphylaxis.as_view(), name="about-prophylaxis"),
    path("about/ult/", view=AboutULT.as_view(), name="about-ult"),
    path("about/<treatment>", view=TreatmentAbout.as_view(), name="about"),
    path("<slug:username>/", view=IndexView.as_view(), name="index"),
    path("<slug:username>/flare/", FlareView.as_view(), name="flare"),
    path("<slug:username>/prophylaxis/", ProphylaxisView.as_view(), name="prophylaxis"),
    path("<slug:username>/ult/", ULTView.as_view(), name="ult"),
    path("<treatment>/<slug:slug>/", view=TreatmentDetail.as_view(), name="detail"),
    path("<slug:username>/list/<treatment>/", view=TreatmentList.as_view(), name="list"),
    path("<slug:username>/create/<treatment>/", view=TreatmentCreate.as_view(), name="create"),
    path(
        "<slug:username>/create/flareaid/<slug:slug>/<treatment>/",
        view=FlareAidTreatmentCreate.as_view(),
        name="flareaid-create",
    ),
    path("<slug:username>/create/ppx/<treatment>/", view=ProphylaxisCreate.as_view(), name="prophylaxis-create"),
    path("update/<treatment>/<slug:slug>/", view=TreatmentUpdate.as_view(), name="update"),
]

goutdotcom/ult/urls.py
from django.urls import path

from .views import ULTCreate, ULTDetail, ULTUpdate

app_name = "ult"
urlpatterns = [
    path("create/", view=ULTCreate.as_view(), name="create"),
    path("<username>/create/", view=ULTCreate.as_view(), name="user-create"),
    path("<int:pk>/", view=ULTDetail.as_view(), name="detail"),
    path("<slug:slug>/", view=ULTDetail.as_view(), name="user-detail"),
    path("update/<int:pk>/", view=ULTUpdate.as_view(), name="update"),
    path("<slug:slug>/update/", view=ULTUpdate.as_view(), name="user-update"),
]

goutdotcom/users/urls.py
from django.urls import path

from goutdotcom.users.views import (
    provider_patient_list_view,
    user_create_view,
    user_detail_view,
    user_provider_detail_view,
    user_provider_update_view,
    user_redirect_view,
    user_update_view,
)

app_name = "users"
urlpatterns = [
    path("create/", view=user_create_view, name="create"),
    path("provider/<str:username>/patients/", view=provider_patient_list_view, name="provider-patient-list"),
    path("update/<str:username>/", view=user_provider_update_view, name="provider-update"),
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
    path("<int:pk>/", view=user_provider_detail_view, name="provider-user-detail"),
]

goutdotcom/flareaid/forms.py
from crispy_forms.helper import FormHelper
from crispy_forms.layout import HTML, ButtonHolder, Div, Fieldset, Layout, Submit
from django import forms
from django.forms import HiddenInput

from ..flare.models import Flare
from .models import FlareAid


class FlareAidForm(forms.ModelForm):
    class Meta:
        model = FlareAid
        fields = (
            "perfect_health",
            "monoarticular",
        )

    def __init__(self, *args, **kwargs):
        # Define self.flare from kwargs before calling super, which overwrites the kwargs
        # pop() flare from kwargs to set form self.flare to the Flare model instance passed to the FlareAidCreate view
        self.flare = kwargs.pop("flare", None)
        self.no_user = kwargs.pop("no_user", False)
        self.angina = kwargs.pop("angina", None)
        self.CHF = kwargs.pop("chf", None)
        self.heartattack = kwargs.pop("heartattack", None)
        self.hypertension = kwargs.pop("hypertension", None)
        self.PVD = kwargs.pop("pvd", None)
        self.stroke = kwargs.pop("stroke", None)
        super(FlareAidForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.layout = Layout(
            Fieldset(
                "",
                "perfect_health",
                HTML(
                    """
                    <hr size="6" color="white" id="perfect_health-line">
                    """
                ),
                "monoarticular",
                HTML(
                    """
                    <hr size="6" color="white" id="monoarticular-line">
                    """
                ),
                Div(
                    HTML(
                        """
                        <h2>Do you have a history of:</h2>
                        """
                    ),
                    HTML(
                        """
                        {% load crispy_forms_tags %}
                        {% crispy anticoagulation_form %}
                        """
                    ),
                    HTML(
                        """
                        {% load crispy_forms_tags %}
                        {% crispy bleed_form %}
                        """
                    ),
                    HTML(
                        """
                        {% load crispy_forms_tags %}
                        {% crispy CKD_form %}
                        """
                    ),
                    HTML(
                        """
                        {% load crispy_forms_tags %}
                        {% crispy colchicine_interactions_form %}
                        """
                    ),
                    HTML(
                        """
                        {% load crispy_forms_tags %}
                        {% crispy diabetes_form %}
                        """
                    ),
                    HTML(
                        """
                        {% load crispy_forms_tags %}
                        {% crispy heartattack_form %}
                        """
                    ),
                    HTML(
                        """
                        {% load crispy_forms_tags %}
                        {% crispy IBD_form %}
                        """
                    ),
                    HTML(
                        """
                        {% load crispy_forms_tags %}
                        {% crispy osteoporosis_form %}
                        """
                    ),
                    HTML(
                        """
                        {% load crispy_forms_tags %}
                        {% crispy stroke_form %}
                        """
                    ),
                    HTML(
                        """
                    <hr size="6" color="white">
                    """
                    ),
                    css_id="subfields",
                ),
            ),
            ButtonHolder(Submit("submit", "Submit", css_class="button white")),
        )
        # Check if there is a Flare associated with FlareAid and hide monoarticular field if so, value will be set in the view, also have to remove white line for style by layout[index]
        if self.flare:
            if self.flare.monoarticular == True or self.flare.monoarticular == False:
                self.fields["monoarticular"].widget = HiddenInput()
                self.helper.layout[0].pop(3)
            if self.no_user == True:
                self.helper.layout[0][3].pop(6)
                self.helper.layout[0][3].pop(8)
                if (
                    self.angina.value == True
                    or self.CHF.value == True
                    or self.heartattack.value == True
                    or self.hypertension.value == True
                    or self.PVD.value == True
                    or self.stroke.value == True
                ):
                    self.fields["perfect_health"].initial = False
                    self.fields["perfect_health"].widget = HiddenInput()
            else:
                if (
                    self.angina.value == True
                    or self.CHF.value == True
                    or self.heartattack.value == True
                    or self.hypertension.value == True
                    or self.PVD.value == True
                    or self.stroke.value == True
                ):
                    self.fields["perfect_health"].initial = False
                    self.fields["perfect_health"].widget = HiddenInput()

goutdotcom/ppxaid/forms.py
from crispy_forms.helper import FormHelper
from crispy_forms.layout import HTML, ButtonHolder, Div, Fieldset, Layout, Submit
from django import forms
from django.forms import HiddenInput

from ..ultaid.models import ULTAid
from .models import PPxAid


class PPxAidForm(forms.ModelForm):
    class Meta:
        model = PPxAid
        fields = ("perfect_health",)

    def __init__(self, *args, **kwargs):
        # Define self.flare from kwargs before calling super, which overwrites the kwargs
        # pop() flare from kwargs to set form self.flare to the Flare model instance passed to the FlareAidCreate view
        self.ultaid = kwargs.pop("ultaid", None)
        self.no_user = kwargs.pop("no_user", False)
        self.ckd = kwargs.pop("ckd", None)
        self.heartattack = kwargs.pop("heartattack", None)
        self.stroke = kwargs.pop("stroke", None)
        super(PPxAidForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.layout = Layout(
            Fieldset(
                "",
                "perfect_health",
                HTML(
                    """
                    <hr size="6" color="white">
                    """
                ),
                Div(
                    HTML(
                        """
                        <h2>Do you have a history of:</h2>
                        """
                    ),
                    HTML(
                        """
                        {% load crispy_forms_tags %}
                        {% crispy anticoagulation_form %}
                        """
                    ),
                    HTML(
                        """
                        {% load crispy_forms_tags %}
                        {% crispy bleed_form %}
                        """
                    ),
                    HTML(
                        """
                        {% load crispy_forms_tags %}
                        {% crispy CKD_form %}
                        """
                    ),
                    HTML(
                        """
                        {% load crispy_forms_tags %}
                        {% crispy colchicine_interactions_form %}
                        """
                    ),
                    HTML(
                        """
                        {% load crispy_forms_tags %}
                        {% crispy diabetes_form %}
                        """
                    ),
                    HTML(
                        """
                        {% load crispy_forms_tags %}
                        {% crispy heartattack_form %}
                        """
                    ),
                    HTML(
                        """
                        {% load crispy_forms_tags %}
                        {% crispy IBD_form %}
                        """
                    ),
                    HTML(
                        """
                        {% load crispy_forms_tags %}
                        {% crispy osteoporosis_form %}
                        """
                    ),
                    HTML(
                        """
                        {% load crispy_forms_tags %}
                        {% crispy stroke_form %}
                        """
                    ),
                    HTML(
                        """
                    <hr size="6" color="white">
                    """
                    ),
                    css_id="subfields",
                ),
            ),
            ButtonHolder(Submit("submit", "Submit", css_class="button white")),
        )
        # Check if there is a ULTAid associated with PPxAid and hide fields passed in kwargs if so, value will be set in the view
        if self.ckd:
            self.helper.layout[0][2].pop(3)
        if self.heartattack:
            self.helper.layout[0][2].pop(5)
        if self.stroke:
            self.helper.layout[0][2].pop(7)

goutdotcom/templates/users/_bleedrisk.html
{% if object.bleed.value %}
  <div class="col">
    <div class="accordion-item">
      <h2 class="accordion-header" id="panelsStayOpen-headingBleed">
        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
          data-bs-target="#panelsStayOpen-collapseBleed" aria-expanded="false"
          aria-controls="panelsStayOpen-collapseBleed">
          Bleed
        </button>
      </h2>
      <div id="panelsStayOpen-collapseBleed" class="accordion-collapse collapse"
        aria-labelledby="panelsStayOpen-headingBleed">
        <div class="accordion-body">
          <ul>
            <li>History of a major bleed is a relative contraindication to NSAIDs.</li>
          </ul>
        </div>
      </div>
    </div>
  </div>
{% endif %}
{% if object.anticoagulation.value == True %}
<div class="col">
  <div class="accordion-item">
    <h2 class="accordion-header" id="panelsStayOpen-headingAnticoagulation">
      <button class="accordion-button" type="button" data-bs-toggle="collapse"
        data-bs-target="#panelsStayOpen-collapseAnticoagulation" aria-expanded="true"
        aria-controls="panelsStayOpen-collapseAnticoagulation">
        {{ object.anticoagulation|capfirst }}
      </button>
    </h2>
    <div id="panelsStayOpen-collapseAnticoagulation" class="accordion-collapse collapse show"
      aria-labelledby="panelsStayOpen-headingAnticoagulation">
      <div class="accordion-body">
        <ul>
          <li>Anticoagulation is a relative contraindication to the use of <a
              href="{% url 'treatment:about-NSAIDs' %}">NSAIDs</a>.</li>
          {% if object.anticoagulation.apixaban %}
          <li>Apixaban</li>
          {% endif %}
          {% if object.anticoagulation.clopidogrel %}
          <li>Clopidogrel (Plavix)</li>
          {% endif %}
          {% if object.anticoagulation.dabigatran %}
          <li>Dabigatran</li>
          {% endif %}
          {% if object.anticoagulation.enoxaparin %}
          <li>Enoxaparin</li>
          {% endif %}
          {% if object.anticoagulation.rivaroxaban %}
          <li>Rivaroxaban</li>
          {% endif %}
          {% if object.anticoagulation.warfarin %}
          <li>Warfarin (Coumadin)</li>
          {% endif %}
          <li>{{ object.anticoagulation.last_modified }}</li>
        </ul>
      </div>
    </div>
  </div>
</div>
{% endif %}

goutdotcom/templates/users/medicalprofile.html
<div class="row">
  <div class="col">
    <h1>Medical History
      <a class="btn btn-primary btn-lg" href="{% url 'profiles:update-medical' object.username %}"
        role="button">Update</a>
    </h1>
  </div>
</div>
<hr size="6" color="white">

<div class="row">
  {% include 'users/_cellcounts.html' %}
  {% include 'users/_transaminitis.html' %}
  {% include 'users/_ckd.html' %}
  {% include 'users/_bleedrisk.html' %}
  {% include 'users/_cardiovascular.html' %}
  {% include 'users/_comorbidities.html' %}
  {% include 'users/_gout.html' %}
  {% include 'users/_medications.html' %}
</div>

goutdotcom/templates/users/patientprofile.html
    <div class="row">
      <div class="col">
        <h1>{{ object.username|capfirst}}'s Profile
        <a class="btn btn-primary btn-lg" href="{% url 'profiles:update' object.username %}" role="button">Update</a>
        <a class="btn btn-primary btn-lg" href="{% url 'account_email' %}" role="button">E-Mail</a>
        {% if request.user.role == "PROVIDER" %}
        <div class="dropdown">
          <button class="btn btn-primary btn-lg dropdown-toggle" type="button" id="dropdownMenuButton"
            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Flare
          </button>
          <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            <a class="dropdown-item" href="{% url 'flare:user-create' object.username %}">Create</a>
            <a class="dropdown-item"
              href="{% url 'flare:list' object.username %}">List</a>
          </div>
        </div>
        <div class="dropdown">
          <button class="btn btn-primary btn-lg dropdown-toggle" type="button" id="dropdownMenuButton"
            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            FlareAid
          </button>
          <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            <a class="dropdown-item"
              href="{% url 'flareaid:user-create' object.username %}">Create</a>
            <a class="dropdown-item" href="{% url 'flare:list' object.username %}">List</a>
          </div>
        </div>
        <div class="dropdown">
          <button class="btn btn-primary btn-lg dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown"
            aria-haspopup="true" aria-expanded="false">
            ULT
          </button>
          <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            <a class="dropdown-item" href="{% url 'ult:user-detail' object.username %}">Detail</a>
            <a class="dropdown-item" href="{% url 'ult:user-create' object.username %}">{% if object.ult %}Update{% else %}Create{% endif %}</a>
          </div>
        </div>
        <div class="dropdown">
          <button class="btn btn-primary btn-lg dropdown-toggle" type="button" id="dropdownMenuButton"
            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            ULTAid
          </button>
          <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            <a class="dropdown-item" href="{% url 'ultaid:user-detail' object.username %}">Detail</a>
            <a class="dropdown-item"
              href="{% url 'ultaid:user-create' object.username %}">{% if object.ultaid %}Update{% else %}Create{% endif %}</a>
          </div>
        </div>
        <div class="dropdown">
          <button class="btn btn-primary btn-lg dropdown-toggle" type="button" id="dropdownMenuButton"
            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            PPxAid
          </button>
          <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            <a class="dropdown-item" href="{% url 'ppxaid:user-detail' object.username %}">Detail</a>
            <a class="dropdown-item"
              href="{% url 'ppxaid:user-create' object.username %}">{% if object.ppxaid %}Update{% else %}Create{% endif %}</a>
          </div>
        </div>
        <form method="post" action="{% url 'ultplan:create' object.username %}">
          {% csrf_token %}
          <button class="btn btn-primary btn-lg" role="button" id="ultplan-create" type="submit"
            value="treatment">ULTPlan</button>
        </form>
        {% endif %}
        </h1>
      </div>
    </div>
    <hr size="6" color="white">
    <div class="row">
      <div class="col">
        <h2><u>Demographics</u></h2>
        <ul id="main-profile-list">
        {% if object.patientprofile.date_of_birth %}
            <li>Age: {{ object.patientprofile.age }}</li>
        {% endif %}
        {% if object.patientprofile.gender %}
            <li>Gender: {{ object.patientprofile.gender|capfirst }}</li>
        {% endif %}
        {% if object.patientprofile.race %}
          <li>Race: {{ object.patientprofile.race|capfirst }}</li>
        {% endif %}
        {% if object.patientprofile.weight.value %}
          <li><a href="{% url 'vitals:list' 'weight' %}">Weight:
              {{ object.patientprofile.weight }}</a></li>
        {% endif %}
        {% if object.patientprofile.height.value %}
          <li><a href="{% url 'vitals:list' 'height' %}">Height:
              {{ object.patientprofile.height }}</a></li>
        {% endif %}
        {% if object.patientprofile.weight.value and object.patientprofile.height.value %}
          <li>BMI: {{ object.patientprofile.BMI|stringformat:".1f" }}</li>
        {% endif %}
        </ul>
      </div>
    </div>

goutdotcom/templates/users/providerprofile.html
{% if object == request.user %}
<div class="row">
  <div class="col">
    <h1>{{ object.username|capfirst}}'s Profile
      <a class="btn btn-primary btn-lg"
        href="{% url 'profiles:provider-update' request.user.username %}" role="button">Update</a>
      <a class="btn btn-primary btn-lg"
        href="{% url 'users:provider-patient-list' request.user.username %}"
        role="button">Patients</a>
        <a class="btn btn-primary btn-lg" href="{% url 'account_email' %}" role="button">E-Mail</a>
      <a class="btn btn-primary btn-lg" href="{% url 'users:create' %}" role="button">Create Patient</a>
    </h1>
  </div>
</div>
{% endif %}

goutdotcom/templates/users/provideruser_form.html
{% extends "base_form.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}{% if form.instance.pk %}Edit{% else %}Create{% endif %}User{% endblock title %}

{% block header %}
{% if form.instance.pk %}
<h1>Edit User</h1>
{% else %}
<h1>Create user</h1>
{% endif %}
{% endblock header %}
{% block form %}
{% if form.instance.pk %}
<form method="post" action="{% url 'ultaid:update' object.pk %}">
  {% csrf_token %}
  {% crispy form %}
</form>
{% else %}
{% if view.kwargs.ult %}
<form method="post" action="{% url 'users:update' %}" %}">
  {% csrf_token %}
  {% crispy form %}
</form>
{% else %}
<form method="post" action="{% url 'users:create' %}" %}">
  {% csrf_token %}
  {% crispy form %}
</form>
{% endif %}
{% endif %}
{% endblock form %}

goutdotcom/templates/users/socialprofile.html
<div class="container content-container">
    <h2><a href="{% url 'profiles:update-social' request.user request.user.socialprofile.pk %}">Social History</a></h2>
      {% if object.socialprofile.alcohol.value %}
      <ul>
        <li>Alcohol</li>
        {% if object.socialprofile.alcohol.number %}
        <li>Quantity per week: {{ object.socialprofile.alcohol.number }} <a
            href="https://en.wikipedia.org/wiki/Standard_drink" target="_blank">drinks</a></li>
        {% endif %}
        {% if object.socialprofile.alcohol.beer or object.socialprofile.alcohol.wine or object.socialprofile.alcohol.liquor %}
        <li>Types of Alcohol</li>
        <ul>
          {% if object.socialprofile.alcohol.beer %}
          <li>Beer</li>
          {% endif %}
          {% if object.socialprofile.alcohol.wine %}
          <li>Wine</li>
          {% endif %}
          {% if object.socialprofile.alcohol.liquor %}
          <li>Liquor</li>
          {% endif %}
        </ul>
        {% endif %}
        {% else %}
        {% endif %}
      </ul>
      {% if object.socialprofile.fructose.value %}
      <ul>
        <li>Fructose</li>
      </ul>
      {% endif %}
      {% if object.socialprofile.shellfish.value %}
      <ul>
        <li>Shellfish</li>
      </ul>
      {% endif %}
</div>

goutdotcom/templates/users/user_detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}User: {{ object.username }}{% endblock %}

{% block content %}
<main class="container profile-container">
  {% if object.role == "PATIENT" %}
    {% if object.patientprofile %}
      {% include "users/patientprofile.html" %}
    {% endif %}
    <hr size="6" color="white">
    {% if object.medicalprofile %}
      {% include "users/medicalprofile.html" %}
    {% endif %}
  {% elif object.role == "PROVIDER" %}
      {% include "users/providerprofile.html" %}
  {% else %}
  bleh
  {% endif %}
</main>
<footer>
</footer>
{% endblock content %}
{% block inline_javascript %}
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
  integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
{% endblock inline_javascript %}

goutdotcom/templates/users/user_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}{{ user.username }}{% endblock %}

{% block content %}
  <h1>{{ user.username }}</h1>
  <form class="form-horizontal" method="post" action="{% url 'users:update' %}">
    {% csrf_token %}
    {{ form|crispy }}
    <div class="control-group">
      <div class="controls">
        <button type="submit" class="btn btn-primary">Update</button>
      </div>
    </div>
  </form>
{% endblock %}
{% block inline_javascript %}
{% endblock inline_javascript %}