config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView

urlpatterns = [
    path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path("about/", TemplateView.as_view(template_name="pages/about.html"), name="about"),
    path("about/gout/", TemplateView.as_view(template_name="pages/about_gout.html"), name="about-gout"),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("goutdotcom.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
    # Reference for app URLs with Cookiecutter-Django: https://stackoverflow.com/questions/39838290/is-there-a-command-for-creating-an-app-using-cookiecutter-django
    path("profiles/", include(("goutdotcom.profiles.urls"), namespace="profiles")),
    path("lab/", include(("goutdotcom.lab.urls"), namespace="lab")),
    path("flare/", include(("goutdotcom.flare.urls"), namespace="flare")),
    path("flareaid/", include(("goutdotcom.flareaid.urls"), namespace="flareaid")),
    path("history/", include(("goutdotcom.history.urls"), namespace="history")),
    path("ppxaid/", include(("goutdotcom.ppxaid.urls"), namespace="ppxaid")),
    path("ult/", include(("goutdotcom.ult.urls"), namespace="ult")),
    path("ultaid/", include(("goutdotcom.ultaid.urls"), namespace="ultaid")),
    path("ultplan/", include(("goutdotcom.ultplan.urls"), namespace="ultplan")),
    path("treatment/", include(("goutdotcom.treatment.urls"), namespace="treatment")),
    path("vitals/", include(("goutdotcom.vitals.urls"), namespace="vitals")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

goutdotcom/flare/urls.py
from django.urls import path

from .views import AboutFlares, FlareCreate, FlareDetail, FlareList, FlareUpdate

app_name = "flare"
urlpatterns = [
    path("about/", view=AboutFlares.as_view(), name="about"),
    path("create/", view=FlareCreate.as_view(), name="create"),
    path("<int:pk>/", view=FlareDetail.as_view(), name="detail"),
    path("<slug:slug>/", view=FlareDetail.as_view(), name="user-detail"),
    path("<slug:username>/create/", view=FlareCreate.as_view(), name="user-create"),
    path("<slug:slug>/update/", view=FlareUpdate.as_view(), name="update"),
    path("list/<slug:username>/", view=FlareList.as_view(), name="list"),
]

goutdotcom/lab/urls.py
from django.urls import path

from .views import (
    IndexView,
    LabAbout,
    LabCheckCreate,
    LabCheckUpdate,
    LabCreate,
    LabDetail,
    LabList,
    LabUpdate,
)

app_name = "lab"
urlpatterns = [
    path("", view=IndexView.as_view(), name="index"),
    path("about/<lab>/", view=LabAbout.as_view(), name="about"),
    path("create/labcheck/", view=LabCheckCreate.as_view(), name="labcheck-create"),
    path("create/<lab>/", view=LabCreate.as_view(), name="create"),
    path("<slug:username>/create/<lab>/", view=LabCreate.as_view(), name="user-create"),
    path("create/<lab>/ultplan/<int:ultplan>/", view=LabCreate.as_view(), name="single-ultplan-create"),
    path("<slug:username>/list/<lab>/", view=LabList.as_view(), name="list"),
    path("update/labcheck/<slug:slug>/", view=LabCheckUpdate.as_view(), name="labcheck-update"),
    path("update/<lab>/<slug:slug>/", view=LabUpdate.as_view(), name="update"),
    path("<lab>/<slug:slug>/", view=LabDetail.as_view(), name="detail"),
]

goutdotcom/ppxaid/urls.py
from django.urls import path

from .views import PPxAidCreate, PPxAidDetail, PPxAidUpdate

app_name = "ppxaid"
urlpatterns = [
    path("create/", view=PPxAidCreate.as_view(), name="create"),
    path("<int:pk>/", view=PPxAidDetail.as_view(), name="detail"),
    path("<slug:slug>/", view=PPxAidDetail.as_view(), name="user-detail"),
    path("<slug:slug>/update/", view=PPxAidUpdate.as_view(), name="update"),
    path("create/ultaid/<int:pk>/", view=PPxAidCreate.as_view(), name="ultaid-create"),
    path("<slug:username>/create/", view=PPxAidCreate.as_view(), name="user-create"),
    path("<slug:username>/create/ultaid/<slug:ultaid>/", view=PPxAidCreate.as_view(), name="user-ultaid-create"),
]

goutdotcom/ult/urls.py
from django.urls import path

from .views import ULTCreate, ULTDetail, ULTUpdate

app_name = "ult"
urlpatterns = [
    path("create/", view=ULTCreate.as_view(), name="create"),
    path("<username>/create/", view=ULTCreate.as_view(), name="user-create"),
    path("<int:pk>/", view=ULTDetail.as_view(), name="detail"),
    path("<slug:slug>/", view=ULTDetail.as_view(), name="user-detail"),
    path("update/<int:pk>/", view=ULTUpdate.as_view(), name="update"),
    path("<slug:slug>/update/", view=ULTUpdate.as_view(), name="user-update"),
]

goutdotcom/ultaid/urls.py
from django.urls import path

from .views import ULTAidCreate, ULTAidDetail, ULTAidUpdate

app_name = "ultaid"
urlpatterns = [
    path("create/", view=ULTAidCreate.as_view(), name="create"),
    # URL for creating ULTAid from ULT with anonymous User
    path("create/ult/<int:ult>/", view=ULTAidCreate.as_view(), name="ult-create"),
    path("<username>/create/", view=ULTAidCreate.as_view(), name="user-create"),
    path("<username>/create/ult/<slug:ult>/", view=ULTAidCreate.as_view(), name="user-ult-create"),
    path("<int:pk>/", view=ULTAidDetail.as_view(), name="detail"),
    path("<slug:slug>/", view=ULTAidDetail.as_view(), name="user-detail"),
    path("<slug:slug>/update/", view=ULTAidUpdate.as_view(), name="update"),
]

goutdotcom/ultaid/models.py
from datetime import timedelta

from django.conf import settings
from django.db import models
from django.urls import reverse, reverse_lazy
from django.utils.safestring import mark_safe
from django.utils.text import format_lazy, slugify
from django_extensions.db.models import TimeStampedModel

from ..history.models import (
    CKD,
    AllopurinolHypersensitivity,
    Erosions,
    FebuxostatHypersensitivity,
    HeartAttack,
    OrganTransplant,
    Stroke,
    Tophi,
    XOIInteractions,
)
from ..ult.models import ULT
from ..ultplan.models import ULTPlan
from .choices import *


class ULTAid(TimeStampedModel):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True)
    ult = models.OneToOneField(
        ULT,
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        default=None,
    )
    ultplan = models.OneToOneField(
        ULTPlan,
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        default=None,
    )
    need = models.BooleanField(
        choices=BOOL_CHOICES,
        verbose_name="Need ULT?",
        help_text=format_lazy("""Do you need <a href='{}' target='_blank'>ULT</a>?""", reverse_lazy("ult:create")),
        null=True,
        blank=True,
    )
    want = models.BooleanField(
        choices=BOOL_CHOICES,
        verbose_name="Want ULT?",
        help_text="Will you take daily medication to get rid of your gout?",
        null=True,
        blank=True,
    )
    ckd = models.ForeignKey(
        CKD,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
    )
    XOI_interactions = models.ForeignKey(
        XOIInteractions,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
    )
    organ_transplant = models.ForeignKey(
        OrganTransplant,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
    )
    allopurinol_hypersensitivity = models.ForeignKey(
        AllopurinolHypersensitivity,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        help_text=mark_safe(
            "Have you ever had a <a href='https://www.nhs.uk/medicines/allopurinol/#:~:text=to%20avoid%20dehydration.-,Serious%20side%20effects,-Skin%20rashes' target='_blank'>drug-reaction to allopurinol</a>?"
        ),
    )
    febuxostat_hypersensitivity = models.ForeignKey(
        FebuxostatHypersensitivity,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        help_text=mark_safe(
            "Have you ever had a <a href='https://www.rheumatology.org/I-Am-A/Patient-Caregiver/Treatments/Febuxostat-Uloric#:~:text=Side%20Effects,not%20be%20stopped.' target='_blank'>drug-reaction to febuxostat</a>?"
        ),
    )
    heartattack = models.ForeignKey(
        HeartAttack,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
    )
    stroke = models.ForeignKey(
        Stroke,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
    )
    erosions = models.ForeignKey(
        Erosions,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
    )
    tophi = models.ForeignKey(
        Tophi,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
    )
    creator = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        null=True,
        related_name="ultaid_creator",
    )
    slug = models.SlugField(max_length=200, null=True, blank=True)

    def save(self, *args, **kwargs):
        # If ULTAid has a User, it should have a slug
        if self.user:
            # Check if there's a slug
            if not self.slug:
                # If no slug, it is a newly created object and needs slug set
                self.slug = slugify(self.user.username)
        super(ULTAid, self).save(*args, **kwargs)

    def decision_aid(self):
        """Function that evaluates ULTAid fields and returns a dictionary containing recommendations for ULT and other pertinent facts to the template for presentation.

        returns {dict}: {dict containing drug, dose, goal uric acid, whether or not the patient is on dialysis, whether or not he or she should see a rheumatologist, and whether or not they are unwilling to take ULT.}"""

        # Create dict to return at end of function after modification for User-provided variables
        ult_choice = {
            "drug": "allopurinol",
            "dose": 100,
            "goal_urate": 6.0,
            "titration_lab_interval": timedelta(days=42),
            "dialysis": False,
            "rheumatologist": False,
            "need": True,
            "want": True,
        }

        # Check if User both needs and wants ULT
        if self.need == True and self.want == True:
            # Check if there are any red flags to computered-ULT
            if self.XOI_interactions.value == True or self.organ_transplant.value == True:
                ult_choice["rheumatologist"] = True

            # Check if User has CKD +/- is on dialysis
            if self.ckd.value == True:
                if self.ckd.dialysis == True:
                    ult_choice["dialysis"] = True
                # Check CKD stage, dose-adjsut ULT if >= stage 3
                if self.ckd.stage != None:
                    if ult_choice["drug"] == "febuxostat":
                        if self.ckd.stage < 3:
                            ult_choice["dose"] = 40
                        else:
                            ult_choice["dose"] = 20
                    else:
                        if self.ckd.stage < 3:
                            ult_choice["dose"] = 100
                        else:
                            ult_choice["dose"] = 50

            # Check if prior hypersensitivity to allopurinol, choose febuxostat if so
            if self.allopurinol_hypersensitivity.value == True:
                if (
                    # Check if User has febuxostat hypersensitivity or other relative contraindication to febuxostat
                    # Should see rheumatologist if so
                    self.febuxostat_hypersensitivity.value == True
                    or self.heartattack.value == True
                    or self.stroke.value == True
                ):
                    ult_choice["rheumatologist"] = True
                ult_choice["drug"] = "febuxostat"
                # Dose adjust for CKD
                if self.ckd.value == True:
                    if self.ckd.stage != None:
                        if self.ckd.stage < 3:
                            ult_choice["dose"] = 40
                        else:
                            ult_choice["dose"] = 20
                    else:
                        ult_choice["dose"] = 20
                else:
                    ult_choice["dose"] = 40

            # Check if prior hypersensitivity to febuxostat, choose allopurinol if so
            if self.febuxostat_hypersensitivity.value == True:
                # Check if User has allopurinol hypersensitivity
                # Should see rheumatologist if so
                if self.allopurinol_hypersensitivity.value == True:
                    ult_choice["rheumatologist"] = True
                # Dose adjust for CKD
                if self.ckd.value == True:
                    if self.ckd.stage != None:
                        if self.ckd.stage < 3:
                            ult_choice["dose"] = 100
                    else:
                        ult_choice["dose"] = 50
            # Check if the ULTAid has an associated User and if the User has a ULT associated with his/her profile
            if self.user:
                try:
                    self.ult = self.user.ult
                except:
                    self.ult = None
                # If there's a ULT, check if there are erosions or tophi and adjust goal_urate per ACR guidelines if so
                if self.ult != None:
                    if self.ult.erosions.value == True or self.ult.tophi.value == True:
                        ult_choice["goal_urate"] = 5.0
        # Check completeness of need/want fields for return dict
        elif self.need == False and self.want == True:
            ult_choice["need"] = False
        elif self.need == True and self.want == False:
            ult_choice["want"] = False
        else:
            ult_choice["need"] = True
            ult_choice["want"] = True
        # Return ult_choice dictionary for template rendering
        return ult_choice

    def get_absolute_url(self):
        if self.user:
            return reverse("ultaid:user-detail", kwargs={"slug": self.slug})
        else:
            return reverse("ultaid:detail", kwargs={"pk": self.pk})

    def __str__(self):
        if (
            self.decision_aid()["rheumatologist"] != True
            and self.decision_aid()["dialysis"] != True
            and self.decision_aid()["need"] == True
            and self.decision_aid()["want"] == True
        ):
            return f"{self.decision_aid()['drug']} {self.decision_aid()['dose']} mg daily"
        elif self.decision_aid()["rheumatologist"] == True:
            return "Rheumatologist"
        elif self.decision_aid()["dialysis"] == True:
            return "Dialysis"
        elif self.decision_aid()["need"] == False:
            return "ULT not indicated"
        elif self.decision_aid()["want"] == False:
            return "ULT not desired"
        else:
            return "Error"

goutdotcom/templates/ultaid/_header.html
{% load ultaid_extras %}
  {% if request.user.is_authenticated %}
    {% if object.slug %}
      <a class="btn btn-primary btn-lg" href="{% url 'ultaid:user-create' object.user.username %}" role="button" style="float: right;">Update</a>
      <h1>{{ object.slug }}'s ULTAid</h1>
    {% else %}
      <a class="btn btn-primary btn-lg" href="{% url 'ultaid:create' %}" role="button"
        style="float: right;">Recalculate</a>
      <h1>ULTAid {{ object.created|date }}</h1>
    {% endif %}
{% else %}
    <a class="btn btn-primary btn-lg" href="{% url 'ultaid:create' %}" role="button" style="float: right;">Recalculate</a>
  {% if object.slug %}
    <h1>{{ object.slug }}'s ULTAid</h1>
  {% else %}
    <h1>ULTAid {{ object.created }}</h1>
  {% endif %}
{% endif %}
<div class="row">
  <div class="col">
    {% if object.decision_aid|get_key:'want' == False %}
      <h2>ULT not desired</h2>
      <p>You indicated you won't take medication daily to get rid of your gout.
      {% if object.decision_aid|get_key:'need' == True %}
        That's unfortunate because ULT is indicated for your gout based on your report or the Gouthelper <a
          href="{% url 'ult:create' %}" target="_blank">ULT calculator</a>! Gout sucks and it can be completely
        eliminated with medications.
      {% endif %}
      </p>
    {% elif object.decision_aid|get_key:'need' == False %}
      <h2>ULT not indicated</h2>
      <p>You indicated that you don't need ULT. This could either be from the Gouthelper <a
          href="{% url 'ult:create' %}" target="_blank">ULT calculator</a> or from the advice of your doctor.</p>
    {% elif object.decision_aid|get_key:'dialysis' == True %}
      <h2><u>Dialysis</u></h2>
      <p>Dialysis filters off uric acid like a healthy set of kidneys would. Thus most people who are on dialysis
        don't need ULT.</p>
    {% elif object.decision_aid|get_key:'rheumatologist' == True %}
      <h2><u>Rheumatologist</u></h2>
      <p>Your medical situation is complicated enough that you should see a rheumatologist for the next step in your gout care.</p>
    {% else %}
      <h2><u>Medication</u>: <a
          href="{% url 'treatment:about' object.decision_aid|get_key:'drug' %}">{{ object.decision_aid|get_key:'drug'|capfirst }}</a>
      </h2>
      </div>
      <div class="col">
        <h2><u>Prophylaxis</u>:
          {% if request.user.is_authenticated %}
            {% if request.user.role == "PROVIDER" %}
              {% if object.user %}
                {% if object.user.ppxaid %}
                <a href="{% url 'ppxaid:user-detail' slug=object.user.username%}">{{ ultaid.ppxaid }}</a>
                {% else %}
                  <a class="btn btn-primary btn-lg" href="{% url 'ppxaid:user-ultaid-create' username=object.user.username ultaid=object.user.username %}"
                    role="button" style="float: none;">Create PPxAid</a>
                {% endif %}
              {% else %}
                {% if object.ppxaid %}
                  <a href="{% url 'ppxaid:detail' object.ppxaid.pk %}">{{ object.ppxaid }}</a>
                {% else %}
                  <a class="btn btn-primary btn-lg"
                    href="{% url 'ppxaid:ultaid-create' pk=object.pk %}"
                    role="button" style="float: none;">Create PPxAid</a>
                {% endif %}
              {% endif %}
            {% elif object.user.role == "PATIENT" %}
              {% if request.user.ppxaid %}
              <a href="{% url 'ppxaid:user-detail' slug=request.user.username%}">{{ ultaid.ppxaid }}</a>
              {% else %}
              <a class="btn btn-primary btn-lg"
                href="{% url 'ppxaid:user-ultaid-create' username=request.user.username ultaid=request.user.username %}"
                role="button" style="float: none;">Create PPxAid</a>
              {% endif %}
            {% endif %}
          {% else %}
            {% if object.ppxaid %}
              <a href="{% url 'treatment:about' object.ppxaid.decision_aid|get_key:'drug' %}">
              {{ object.ppxaid.decision_aid|get_key:'drug' }}
              </a>
            {% else %}
            <a class="btn btn-primary btn-lg" href="{% url 'ppxaid:ultaid-create' pk=object.pk %}" role="button"
              style="float: none;">Create PPxAid</a>
            {% endif %}
          {% endif %}
        </h2>
      </div>
    </div>
    <div class="row">
      <div class="col">

    <h3><u>Frequency of lab checks</u>: every 6 weeks</h3>
    <p>We recommend checking labs every 6 weeks. In addition to <a href="{% url 'lab:about' 'urate' %}">uric acid</a>, <a
        href="{% url 'lab:about' 'creatinine' %}">creatinine</a>, <a href="{% url 'lab:about' 'hemoglobin' %}">hemoglobin</a>,
      <a href="{% url 'lab:about' 'platelets' %}">platelets</a>, <a href="{% url 'lab:about' 'WBC' %}">WBC</a>, <a
        href="{% url 'lab:about' 'AST' %}">AST</a>,
      and
      <a href="{% url 'lab:about' 'ALT' %}">ALT</a> are checked with every blood draw to monitor for clinically significant changes.</p>
    <h3>
      {% if object.modified %}
      Modified {{ object.modified }}
      {% else %}
      Created {{ object.created }}
      {% endif %}
      {% if object.ult %}
        {{ object.ult }}
      {% endif %}
    </h3>
      {% if request.user.is_authenticated %}
        {% if object.decision_aid|get_key:'rheumatologist' == True or object.decision_aid|get_key:'dialysis' == True or object.decision_aid|get_key:'need' == False or object.decision_aid|get_key:'want' == False %}
        {% else %}
          {% if request.user.ppxaid %}
          <form method="post" action="{% url 'ultplan:create' object.user.username %}">
            {% csrf_token %}
            <button class="btn btn-primary btn-lg" role="button" id="ultplan-create" type="submit"
              value="treatment">ULTPlan</button>
          </form>
          {% else %}
          {% endif %}
        {% endif %}
      {% endif %}
      </div>
      <div class="col">
      <h3><u>Titration dose</u>: {{ object.decision_aid|get_key:'dose'|capfirst }} mg daily</h3>
      <p>With every lab check, increase the dose of {{ object.decision_aid|get_key:'drug' }} by
        {{ object.decision_aid|get_key:'dose'|capfirst }} mg daily until the
        uric acid is at <a href="#goal">goal</a>.</p>
      <h3 id="goal"><u>Goal uric acid</u>: {{ object.decision_aid|get_key:'goal_urate' }} mg/dL</h3>
      <p>Gout will be best eliminated with a <a href="NEED PAGE ABOUT GOAL URIC ACID">goal uric acid</a> of {{ object.decision_aid|get_key:'goal_urate' }} mg/dL.</p>
      {% endif %}
  </div>
</div>

<hr class="my-6" color="white">

goutdotcom/templates/ultaid/_references.html
  <h2 class="content-heading"><a id="references">References</a></h2>
  <ol>
    <li id=1>FitzGerald JD, Dalbeth N, Mikuls T, Brignardello-Petersen R, Guyatt G, Abeles AM, Gelber AC, Harrold LR,
      Khanna D, King C, Levy G, Libbey C, Mount D, Pillinger MH, Rosenthal A, Singh JA, Sims JE, Smith BJ, Wenger NS,
      Bae SS, Danve A, Khanna PP, Kim SC, Lenert A, Poon S, Qasim A, Sehra ST, Sharma TSK, Toprover M, Turgunbaev M,
      Zeng L, Zhang MA, Turner AS, Neogi T. 2020 American College of Rheumatology Guideline for the Management of Gout.
      Arthritis Care Res (Hoboken). 2020 Jun;72(6):744-760. doi: 10.1002/acr.24180. PMID: 32391934.<a
        href="https://pubmed.ncbi.nlm.nih.gov/32391934/" target="_blank"> https://doi.org/10.1525/9780520339484-005</a>
    </li>
    <li id=2>Abeles AM, Pillinger MH. Febuxostat and the Black Box Blues. ACR Open Rheumatol. 2019;1(6):343-344.
      Published 2019 Jul 11. doi:10.1002/acr2.11047.<a
        href="https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6858030/" target="_blank">
        https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6858030/</a>
    </li>
  </ol>

goutdotcom/templates/ultaid/references.html
  <h2 class="content-heading"><a id="references">References</a></h2>
  <ol>
    <li id=1>FitzGerald JD, Dalbeth N, Mikuls T, Brignardello-Petersen R, Guyatt G, Abeles AM, Gelber AC, Harrold LR,
      Khanna D, King C, Levy G, Libbey C, Mount D, Pillinger MH, Rosenthal A, Singh JA, Sims JE, Smith BJ, Wenger NS,
      Bae SS, Danve A, Khanna PP, Kim SC, Lenert A, Poon S, Qasim A, Sehra ST, Sharma TSK, Toprover M, Turgunbaev M,
      Zeng L, Zhang MA, Turner AS, Neogi T. 2020 American College of Rheumatology Guideline for the Management of Gout.
      Arthritis Care Res (Hoboken). 2020 Jun;72(6):744-760. doi: 10.1002/acr.24180. PMID: 32391934.<a
        href="https://pubmed.ncbi.nlm.nih.gov/32391934/" target="_blank"> https://doi.org/10.1525/9780520339484-005</a>
    </li>
    <li id=2>Abeles AM, Pillinger MH. Febuxostat and the Black Box Blues. ACR Open Rheumatol. 2019;1(6):343-344.
      Published 2019 Jul 11. doi:10.1002/acr2.11047.<a
        href="https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6858030/" target="_blank">
        https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6858030/</a>
    </li>
  </ol>

goutdotcom/templates/ultaid/ultaid_detail.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<main class="container-fluid content-container">
  <div class="row">
    <div class="col">
      {% block header %}
        {% include 'ultaid/_header.html' %}
      {% endblock header %}
      {% block rationale %}
        {% include 'ultaid/_rationale.html' %}
      {% endblock rationale %}
      {% block references %}
        {% include 'ultaid/_references.html' %}
      {% endblock references %}
    </div>
  </div>
</main>
{% block footer %}
  <footer>
  </footer>
{% endblock footer %}
</main>
{% endblock content %}

{% block inline_javascript %}

{% endblock inline_javascript %}

goutdotcom/templates/ultaid/ultaid_form.html
{% extends "base_form.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}Create ULT Helper{% endblock title %}

{% block header %}
{{ user_ult|json_script:'user_ult' }}
{% if form.instance.pk %}
<h1>{{ object.user.username|capfirst }}'s'} ULT plan</h1>
{% else %}
{% if view.kwargs.username %}
<h1>{{ view.kwargs.username|capfirst }}'s' ULT plan</h1>
{% else %}
<h1>Make a ULT plan</h1>
{% endif %}
{% endif %}
{% endblock header %}

{% block form %}
{% if form.instance.pk %}
<form method="post" action="{% url 'ultaid:update' object.slug %}">
  {% csrf_token %}
  {% crispy form %}
</form>
{% else %}
  {% if view.kwargs.ult %}
    {% if view.kwargs.username %}
      <form method="post" action="{% url 'ultaid:user-ult-create' username=view.kwargs.username ult=view.kwargs.ult %}">
        {% csrf_token %}
        {% crispy form %}
      </form>
    {% else %}
      <form method="post" action="{% url 'ultaid:ult-create' ult=view.kwargs.ult %}">
        {% csrf_token %}
        {% crispy form %}
      </form>
    {% endif %}
  {% else %}
    {% if view.kwargs.username %}
      <form method="post" action="{% url 'ultaid:user-create' username=view.kwargs.username %}">
        {% csrf_token %}
        {% crispy form %}
      </form>
    {% else %}
      <form method="post" action="{% url 'ultaid:create' %}">
        {% csrf_token %}
        {% crispy form %}
      </form>
    {% endif %}
  {% endif %}
{% endif %}
{% endblock form %}


{% block inline_javascript %}
<script>
// this is executed once when the page loads
  $(document).ready(function() {
  ULT_exists_checker();
  // set things up so my function will be called when form fields change
  $('#id_need').change(need_want_checker);
  need_want_checker.call($('#id_need').get(0));
  $('#id_want').change(need_want_checker);
  need_want_checker.call($('#id_want').get(0));
  $('#id_CKD-value').change(CKD_checker);
  CKD_checker.call($('#id_CKD-value').get(0));
  $('#id_organ_transplant-value').change(transplant_checker);
  transplant_checker.call($('#id_organ_transplant-value').get(0));
  });
  jQuery(function ($) {
    var path = window.location.href;
    $('li a').each(function () {
    if (this.href === path) {
    $(this).addClass('active');
    } else {
    $(this).removeClass('active');
    }
    });
  });
</script>
{% endblock inline_javascript %}