config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView

urlpatterns = [
    path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path("about/", TemplateView.as_view(template_name="pages/about.html"), name="about"),
    path("about/gout/", TemplateView.as_view(template_name="pages/about_gout.html"), name="about-gout"),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("goutdotcom.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
    # Reference for app URLs with Cookiecutter-Django: https://stackoverflow.com/questions/39838290/is-there-a-command-for-creating-an-app-using-cookiecutter-django
    path("profiles/", include(("goutdotcom.profiles.urls"), namespace="profiles")),
    path("lab/", include(("goutdotcom.lab.urls"), namespace="lab")),
    path("flare/", include(("goutdotcom.flare.urls"), namespace="flare")),
    path("flareaid/", include(("goutdotcom.flareaid.urls"), namespace="flareaid")),
    path("history/", include(("goutdotcom.history.urls"), namespace="history")),
    path("ppxaid/", include(("goutdotcom.ppxaid.urls"), namespace="ppxaid")),
    path("ult/", include(("goutdotcom.ult.urls"), namespace="ult")),
    path("ultaid/", include(("goutdotcom.ultaid.urls"), namespace="ultaid")),
    path("ultplan/", include(("goutdotcom.ultplan.urls"), namespace="ultplan")),
    path("treatment/", include(("goutdotcom.treatment.urls"), namespace="treatment")),
    path("vitals/", include(("goutdotcom.vitals.urls"), namespace="vitals")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

goutdotcom/flare/urls.py
from django.urls import path

from .views import AboutFlares, FlareCreate, FlareDetail, FlareList, FlareUpdate

app_name = "flare"
urlpatterns = [
    path("about/", view=AboutFlares.as_view(), name="about"),
    path("create/", view=FlareCreate.as_view(), name="create"),
    path("<int:pk>/", view=FlareDetail.as_view(), name="detail"),
    path("<slug:slug>/", view=FlareDetail.as_view(), name="user-detail"),
    path("<slug:username>/create/", view=FlareCreate.as_view(), name="user-create"),
    path("<slug:slug>/update/", view=FlareUpdate.as_view(), name="update"),
    path("list/<slug:username>/", view=FlareList.as_view(), name="list"),
]

goutdotcom/lab/urls.py
from django.urls import path

from .views import (
    IndexView,
    LabAbout,
    LabCheckCreate,
    LabCheckUpdate,
    LabCreate,
    LabDetail,
    LabList,
    LabUpdate,
)

app_name = "lab"
urlpatterns = [
    path("", view=IndexView.as_view(), name="index"),
    path("about/<lab>/", view=LabAbout.as_view(), name="about"),
    path("create/labcheck/", view=LabCheckCreate.as_view(), name="labcheck-create"),
    path("create/<lab>/", view=LabCreate.as_view(), name="create"),
    path("<slug:username>/create/<lab>/", view=LabCreate.as_view(), name="user-create"),
    path("create/<lab>/ultplan/<int:ultplan>/", view=LabCreate.as_view(), name="single-ultplan-create"),
    path("<slug:username>/list/<lab>/", view=LabList.as_view(), name="list"),
    path("update/labcheck/<slug:slug>/", view=LabCheckUpdate.as_view(), name="labcheck-update"),
    path("update/<lab>/<slug:slug>/", view=LabUpdate.as_view(), name="update"),
    path("<lab>/<slug:slug>/", view=LabDetail.as_view(), name="detail"),
]

goutdotcom/ppxaid/urls.py
from django.urls import path

from .views import PPxAidCreate, PPxAidDetail, PPxAidUpdate

app_name = "ppxaid"
urlpatterns = [
    path("create/", view=PPxAidCreate.as_view(), name="create"),
    path("<int:pk>/", view=PPxAidDetail.as_view(), name="detail"),
    path("<slug:slug>/", view=PPxAidDetail.as_view(), name="user-detail"),
    path("<slug:slug>/update/", view=PPxAidUpdate.as_view(), name="update"),
    path("create/ultaid/<int:pk>/", view=PPxAidCreate.as_view(), name="ultaid-create"),
    path("<slug:username>/create/", view=PPxAidCreate.as_view(), name="user-create"),
    path("<slug:username>/create/ultaid/<slug:ultaid>/", view=PPxAidCreate.as_view(), name="user-ultaid-create"),
]

goutdotcom/treatment/urls.py
from django.urls import path

from .views import *

app_name = "treatment"
urlpatterns = [
    path("about/", view=About.as_view(), name="about"),
    path("about/corticosteroids/", view=AboutCorticosteroids.as_view(), name="about-corticosteroids"),
    path("about/flare/", view=AboutFlare.as_view(), name="about-flare"),
    path("about/nsaids/", view=AboutNSAIDs.as_view(), name="about-NSAIDs"),
    path("about/prophylaxis/", view=AboutProphylaxis.as_view(), name="about-prophylaxis"),
    path("about/ult/", view=AboutULT.as_view(), name="about-ult"),
    path("about/<treatment>", view=TreatmentAbout.as_view(), name="about"),
    path("<slug:username>/", view=IndexView.as_view(), name="index"),
    path("<slug:username>/flare/", FlareView.as_view(), name="flare"),
    path("<slug:username>/prophylaxis/", ProphylaxisView.as_view(), name="prophylaxis"),
    path("<slug:username>/ult/", ULTView.as_view(), name="ult"),
    path("<treatment>/<slug:slug>/", view=TreatmentDetail.as_view(), name="detail"),
    path("<slug:username>/list/<treatment>/", view=TreatmentList.as_view(), name="list"),
    path("<slug:username>/create/<treatment>/", view=TreatmentCreate.as_view(), name="create"),
    path(
        "<slug:username>/create/flareaid/<slug:slug>/<treatment>/",
        view=FlareAidTreatmentCreate.as_view(),
        name="flareaid-create",
    ),
    path("<slug:username>/create/ppx/<treatment>/", view=ProphylaxisCreate.as_view(), name="prophylaxis-create"),
    path("update/<treatment>/<slug:slug>/", view=TreatmentUpdate.as_view(), name="update"),
]

goutdotcom/ult/urls.py
from django.urls import path

from .views import ULTCreate, ULTDetail, ULTUpdate

app_name = "ult"
urlpatterns = [
    path("create/", view=ULTCreate.as_view(), name="create"),
    path("<username>/create/", view=ULTCreate.as_view(), name="user-create"),
    path("<int:pk>/", view=ULTDetail.as_view(), name="detail"),
    path("<slug:slug>/", view=ULTDetail.as_view(), name="user-detail"),
    path("update/<int:pk>/", view=ULTUpdate.as_view(), name="update"),
    path("<slug:slug>/update/", view=ULTUpdate.as_view(), name="user-update"),
]

goutdotcom/users/urls.py
from django.urls import path

from goutdotcom.users.views import (
    provider_patient_list_view,
    user_create_view,
    user_detail_view,
    user_provider_detail_view,
    user_provider_update_view,
    user_redirect_view,
    user_update_view,
)

app_name = "users"
urlpatterns = [
    path("create/", view=user_create_view, name="create"),
    path("provider/<str:username>/patients/", view=provider_patient_list_view, name="provider-patient-list"),
    path("update/<str:username>/", view=user_provider_update_view, name="provider-update"),
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
    path("<int:pk>/", view=user_provider_detail_view, name="provider-user-detail"),
]

goutdotcom/flareaid/forms.py
from crispy_forms.helper import FormHelper
from crispy_forms.layout import HTML, ButtonHolder, Div, Fieldset, Layout, Submit
from django import forms
from django.forms import HiddenInput

from ..flare.models import Flare
from .models import FlareAid


class FlareAidForm(forms.ModelForm):
    class Meta:
        model = FlareAid
        fields = (
            "perfect_health",
            "monoarticular",
        )

    def __init__(self, *args, **kwargs):
        # Define self.flare from kwargs before calling super, which overwrites the kwargs
        # pop() flare from kwargs to set form self.flare to the Flare model instance passed to the FlareAidCreate view
        self.flare = kwargs.pop("flare", None)
        self.no_user = kwargs.pop("no_user", False)
        self.angina = kwargs.pop("angina", None)
        self.CHF = kwargs.pop("chf", None)
        self.heartattack = kwargs.pop("heartattack", None)
        self.hypertension = kwargs.pop("hypertension", None)
        self.PVD = kwargs.pop("pvd", None)
        self.stroke = kwargs.pop("stroke", None)
        super(FlareAidForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.layout = Layout(
            Fieldset(
                "",
                "perfect_health",
                HTML(
                    """
                    <hr size="6" color="white" id="perfect_health-line">
                    """
                ),
                "monoarticular",
                HTML(
                    """
                    <hr size="6" color="white" id="monoarticular-line">
                    """
                ),
                Div(
                    HTML(
                        """
                        <h2>Do you have a history of:</h2>
                        """
                    ),
                    HTML(
                        """
                        {% load crispy_forms_tags %}
                        {% crispy anticoagulation_form %}
                        """
                    ),
                    HTML(
                        """
                        {% load crispy_forms_tags %}
                        {% crispy bleed_form %}
                        """
                    ),
                    HTML(
                        """
                        {% load crispy_forms_tags %}
                        {% crispy CKD_form %}
                        """
                    ),
                    HTML(
                        """
                        {% load crispy_forms_tags %}
                        {% crispy colchicine_interactions_form %}
                        """
                    ),
                    HTML(
                        """
                        {% load crispy_forms_tags %}
                        {% crispy diabetes_form %}
                        """
                    ),
                    HTML(
                        """
                        {% load crispy_forms_tags %}
                        {% crispy heartattack_form %}
                        """
                    ),
                    HTML(
                        """
                        {% load crispy_forms_tags %}
                        {% crispy IBD_form %}
                        """
                    ),
                    HTML(
                        """
                        {% load crispy_forms_tags %}
                        {% crispy osteoporosis_form %}
                        """
                    ),
                    HTML(
                        """
                        {% load crispy_forms_tags %}
                        {% crispy stroke_form %}
                        """
                    ),
                    HTML(
                        """
                    <hr size="6" color="white">
                    """
                    ),
                    css_id="subfields",
                ),
            ),
            ButtonHolder(Submit("submit", "Submit", css_class="button white")),
        )
        # Check if there is a Flare associated with FlareAid and hide monoarticular field if so, value will be set in the view, also have to remove white line for style by layout[index]
        if self.flare:
            if self.flare.monoarticular == True or self.flare.monoarticular == False:
                self.fields["monoarticular"].widget = HiddenInput()
                self.helper.layout[0].pop(3)
            if self.no_user == True:
                self.helper.layout[0][3].pop(6)
                self.helper.layout[0][3].pop(8)
                if (
                    self.angina.value == True
                    or self.CHF.value == True
                    or self.heartattack.value == True
                    or self.hypertension.value == True
                    or self.PVD.value == True
                    or self.stroke.value == True
                ):
                    self.fields["perfect_health"].initial = False
                    self.fields["perfect_health"].widget = HiddenInput()
            else:
                if (
                    self.angina.value == True
                    or self.CHF.value == True
                    or self.heartattack.value == True
                    or self.hypertension.value == True
                    or self.PVD.value == True
                    or self.stroke.value == True
                ):
                    self.fields["perfect_health"].initial = False
                    self.fields["perfect_health"].widget = HiddenInput()

goutdotcom/ppxaid/forms.py
from crispy_forms.helper import FormHelper
from crispy_forms.layout import HTML, ButtonHolder, Div, Fieldset, Layout, Submit
from django import forms
from django.forms import HiddenInput

from ..ultaid.models import ULTAid
from .models import PPxAid


class PPxAidForm(forms.ModelForm):
    class Meta:
        model = PPxAid
        fields = ("perfect_health",)

    def __init__(self, *args, **kwargs):
        # Define self.flare from kwargs before calling super, which overwrites the kwargs
        # pop() flare from kwargs to set form self.flare to the Flare model instance passed to the FlareAidCreate view
        self.ultaid = kwargs.pop("ultaid", None)
        self.no_user = kwargs.pop("no_user", False)
        self.ckd = kwargs.pop("ckd", None)
        self.heartattack = kwargs.pop("heartattack", None)
        self.stroke = kwargs.pop("stroke", None)
        super(PPxAidForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.layout = Layout(
            Fieldset(
                "",
                "perfect_health",
                HTML(
                    """
                    <hr size="6" color="white">
                    """
                ),
                Div(
                    HTML(
                        """
                        <h2>Do you have a history of:</h2>
                        """
                    ),
                    HTML(
                        """
                        {% load crispy_forms_tags %}
                        {% crispy anticoagulation_form %}
                        """
                    ),
                    HTML(
                        """
                        {% load crispy_forms_tags %}
                        {% crispy bleed_form %}
                        """
                    ),
                    HTML(
                        """
                        {% load crispy_forms_tags %}
                        {% crispy CKD_form %}
                        """
                    ),
                    HTML(
                        """
                        {% load crispy_forms_tags %}
                        {% crispy colchicine_interactions_form %}
                        """
                    ),
                    HTML(
                        """
                        {% load crispy_forms_tags %}
                        {% crispy diabetes_form %}
                        """
                    ),
                    HTML(
                        """
                        {% load crispy_forms_tags %}
                        {% crispy heartattack_form %}
                        """
                    ),
                    HTML(
                        """
                        {% load crispy_forms_tags %}
                        {% crispy IBD_form %}
                        """
                    ),
                    HTML(
                        """
                        {% load crispy_forms_tags %}
                        {% crispy osteoporosis_form %}
                        """
                    ),
                    HTML(
                        """
                        {% load crispy_forms_tags %}
                        {% crispy stroke_form %}
                        """
                    ),
                    HTML(
                        """
                    <hr size="6" color="white">
                    """
                    ),
                    css_id="subfields",
                ),
            ),
            ButtonHolder(Submit("submit", "Submit", css_class="button white")),
        )
        # Check if there is a ULTAid associated with PPxAid and hide fields passed in kwargs if so, value will be set in the view
        if self.ckd:
            self.helper.layout[0][2].pop(3)
        if self.heartattack:
            self.helper.layout[0][2].pop(5)
        if self.stroke:
            self.helper.layout[0][2].pop(7)

goutdotcom/templates/base.html
{% load static i18n %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="x-ua-compatible" content="ie=edge" />
    <title>{% block title %}Gouthelper{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="description" content="A site for all things gout." />
    <meta name="author" content="Dave Ewart" />
    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js"></script>
    <![endif]-->
    <link rel="icon" href="{% static 'images/favicons/favicon.ico' %}" />
    {% block css %}
    <!-- Latest compiled and minified Bootstrap CSS -->
    <link
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
      crossorigin="anonymous"
    />
    <!-- Your stuff: Third-party CSS libraries go here -->
    <!-- This file stores project-specific CSS -->
    <link href="{% static 'css/project.min.css' %}" rel="stylesheet"/>
    {% endblock %}
    <!-- Le javascript
    ================================================== -->
    {# Placed at the top of the document so pages load faster with defer #}
    {% block javascript %}
    <!-- Bootstrap JS and its dependencies-->
    <script
      src="https://code.jquery.com/jquery-3.6.0.min.js"
      integrity="sha384-vtXRMe3mGCbOeY7l30aIg8H9p3GdeSe4IFlP6G8JMa7o7lXvnz3GFKzPxzJdPfGK"
      crossorigin="anonymous"
    ></script>
    <script
      defer
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
      integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
      crossorigin="anonymous"
    ></script>
    <script
      defer
      src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
      integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
      crossorigin="anonymous"></script>
    <!-- Your stuff: Third-party javascript libraries go here -->
    <!-- place project specific Javascript in this file -->
    <script defer src="{% static 'js/project.js' %}"></script>
    {% endblock javascript %}
  </head>

  <body>
    {% block navbar %}
      {% include "navbar.html" %}
    {% endblock navbar %}

    {% block header %}{% endblock header %}


    <div class="container-fluid">
      {% if messages %} {% for message in messages %}
      <div
        class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}"
      >
        {{ message }}<button
          type="button"
          class="close"
          data-dismiss="alert"
          aria-label="Close"
        >
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      {% endfor %} {% endif %}
      {% block content %}
      <p>Use this document as a way to quick start any new project.</p>
      {% endblock content %}
    </div>
    {% block footer %}{% endblock footer %}
    <!-- /container -->

    {% block modal %}
    {% endblock modal %}
    {% block inline_javascript %}
    {#Script tags with only code, no src (defer by default) #}
    {% endblock inline_javascript %}
  </body>
</html>

goutdotcom/templates/base_form.html
{% extends "base.html" %}

{% block title %} {{ user.username }} {% endblock title %}
{% block content %}
<main>
  {% block header %}{% endblock header %}
  {% block form %}{% endblock form %}
</main>
{% endblock content %}

goutdotcom/templates/navbar.html
{% load static i18n %}
    <nav class="navbar navbar-expand-md  py-1">
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse"
        data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
        aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <a class="navbar-brand" href="{% url 'home' %}">Gouthelper</a>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'about' %}">About</a>
          </li>
          {% if request.user.is_authenticated %}
            {% if request.user.role == "PATIENT" %}
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Calcs
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <a class="dropdown-item" href="{% url 'flare:create' %}">Flare</a>
                  <a class="dropdown-item" href="{% url 'flareaid:create' %}">FlareAid</a>
                  <a class="dropdown-item" href="{% url 'ult:create' %}">ULT</a>
                  <a class="dropdown-item" href="{% url 'ultaid:create' %}">ULTAid</a>
                  <a class="dropdown-item" href="{% url 'ppxaid:create' %}">PPxAid</a>
                </div>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Flares
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <a class="dropdown-item" href="{% url 'flare:user-create' request.user.username %}">Calculator</a>
                  <a class="dropdown-item" href="{% url 'flareaid:user-create' request.user.username  %}">Helper</a>
                  <a class="dropdown-item" href="{% url 'flare:list' request.user.username %}">List</a>
                  <div class="dropdown-divider"></div>
                  <a class="dropdown-item" href="{% url 'flare:about' %}">About</a>
                </div>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  ULT
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  {% if request.user.ult %}
                  <a class="dropdown-item" href="{% url 'ult:user-detail' request.user.username %}">Calculator</a>
                  {% else %}
                  <a class="dropdown-item" href="{% url 'ult:user-create' request.user.username %}">Calculator</a>
                  {% endif %}
                  {% if request.user.ultaid %}
                  <a class="dropdown-item" href="{% url 'ultaid:detail' request.user.ultaid.pk %}">Helper</a>
                  {% else %}
                  <a class="dropdown-item" href="{% url 'ultaid:user-create' request.user.username %}">Helper</a>
                  {% endif %}
                  {% if request.user.ppxaid %}
                  <a class="dropdown-item" href="{% url 'ppxaid:detail' request.user.ppxaid.pk %}">PPx</a>
                  {% else %}
                    {% if request.user.ultaid %}
                    <a class="dropdown-item" href="{% url 'ppxaid:ultaid-create' pk=request.user.ultaid.pk %}">PPx</a>
                    {% else %}
                    <a class="dropdown-item" href="{% url 'ppxaid:create' %}">PPx</a>
                    {% endif %}
                  {% endif %}
                  <div class="dropdown-divider"></div>
                  <a class="dropdown-item" href="{% url 'treatment:about-ult' %}">About</a>
                </div>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  {{ request.user|capfirst }}
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  {% if request.user.ultplan %}
                  <a class="dropdown-item" href="{% url 'ultplan:detail' request.user.ultplan.slug %}">ULTPlan</a>
                  <div class="dropdown-divider"></div>
                  <a class="dropdown-item" href="{% url 'lab:index' %}">Labs</a>
                  {% endif %}
                  <a class="dropdown-item" href="{% url 'treatment:index' request.user.username %}">Treatments</a>
                  <a class="dropdown-item" href="{% url 'users:detail' request.user.username %}">{% trans "Profile" %}</a>
                </div>
              </li>
              {% elif request.user.role == "PROVIDER" %}
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Calcs
                  </a>
                  <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="{% url 'flare:create' %}">Flare</a>
                    <a class="dropdown-item" href="{% url 'flareaid:create' %}">FlareAid</a>
                    <a class="dropdown-item" href="{% url 'ult:create' %}">ULT</a>
                    <a class="dropdown-item" href="{% url 'ultaid:create' %}">ULTAid</a>
                    <a class="dropdown-item" href="{% url 'ppxaid:create' %}">PPxAid</a>
                  </div>
                </li>
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    {{ request.user|capfirst }}
                  </a>
                  <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="{% url 'users:detail' request.user.username %}">{% trans "Profile" %}</a>
                      <a class="dropdown-item" href="{% url 'users:provider-patient-list' request.user.username %}">Patients</a>
                  </div>
                </li>
              {% endif %}
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a class="nav-link" href="{% url 'account_logout' %}">{% trans "Sign Out" %}</a>
              </li>
          {% else %}
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Flares
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="{% url 'flare:create' %}">Calculator</a>
                <a class="dropdown-item" href="{% url 'flareaid:create' %}">Helper</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="{% url 'flare:about' %}">About</a>
              </div>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                ULT
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="{% url 'ult:create' %}">Calculator</a>

                <a class="dropdown-item" href="{% url 'ultaid:create' %}">Helper</a>

                  <a class="dropdown-item" href="{% url 'ppxaid:create' %}">PPx</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="{% url 'treatment:about-ult' %}">About</a>
              </div>
            </li>
          {% endif %}
        </ul>
      </div>
    </nav>